<?xml version="1.0" encoding="utf-8"?><Database Name="QuanLyCuaHangDienThoai" Class="DBAccountDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=HUNGPC\HUNGSQLSERVER;Initial Catalog=QuanLyCuaHangDienThoai;Persist Security Info=True;User ID=hung2207" SettingsObjectName="PhoneManagement.Properties.Settings" SettingsPropertyName="QuanLyCuaHangDienThoaiConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Account" Member="Accounts">
    <Type Name="Account">
      <Column Name="UserName" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PassWord" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TypeAccount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DisplayName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>